const mongoose = require('mongoose');

// Weekly class booking slot generated by the AI Timetable Engine
const slotSchema = new mongoose.Schema({
  day: {
    type: String,
    enum: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    required: true
  },
  startTime: { type: String, required: true }, // Format "HH:mm" (e.g. "09:00")
  endTime: { type: String, required: true },   // Format "HH:mm" (e.g. "10:30")
  subject: { type: String, default: 'Scheduled Lecture / Lab' }
});

const roomSchema = new mongoose.Schema({
  code: { 
    type: String, 
    required: true, 
    unique: true, 
    uppercase: true, 
    trim: true 
  },
  building: { 
    type: String, 
    required: true, 
    trim: true,
    enum: ['E-2 Building', 'Gateway Building', 'Central Library', 'Innovation Hub']
  },
  floor: { 
    type: Number, 
    required: true,
    min: 1,
    max: 5
  },
  type: { 
    type: String, 
    required: true, 
    enum: ['Classroom', 'Seminar Hall', 'Study Pod', 'Computer Lab', 'Discussion Room'],
    default: 'Classroom'
  },
  capacity: { 
    type: Number, 
    required: true,
    default: 35
  },
  status: { 
    type: String, 
    enum: ['empty', 'busy'], 
    default: 'empty' 
  },
  busyVotes: [{
    ipOrUserId: { type: String },
    timestamp: { type: Date, default: Date.now }
  }],
  statusChangedAt: { 
    type: Date, 
    default: Date.now 
  },
  lastUpdated: { 
    type: Date, 
    default: Date.now 
  },
  // AI Weekly Timetable Slots
  weeklySchedule: [slotSchema]
});

module.exports = mongoose.model('Room', roomSchema);